name: smart_vision_analyzer
description: A smart vision analyzer app using ML Kit and camera
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  camera: ^0.11.3
  image_picker: ^1.1.1
  vibration: ^3.1.4
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  # âœ… ML Kit packages (same google_mlkit_commons version)
  google_mlkit_commons: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_image_labeling: ^0.14.0
  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_language_id: ^0.13.0
  google_mlkit_translation: ^0.13.0
  google_mlkit_smart_reply: ^0.7.0
  google_mlkit_entity_extraction: 0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
